# Generated by Django 6.0.2 on 2026-02-15 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="installation",
            name="technicians",
            field=models.ManyToManyField(
                related_name="installations", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="maintenancecontract",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_contracts",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="servicequote",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotes",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="installation",
            name="quote",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="installation",
                to="services.servicequote",
            ),
        ),
    ]
