# Generated by Django 4.2.7 on 2026-02-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("devis", "Devis"),
                            ("réparation", "Réparation"),
                            ("entretien", "Entretien"),
                            ("installation", "Installation"),
                        ],
                        default="devis",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
