# Generated by Django 6.0.2 on 2026-04-05 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
        ("services", "0003_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services",
                to="clients.client",
            ),
        ),
    ]
